#!/usr/bin/env python3
"""Download official Discord developer docs as Markdown into ``docs/discord/``.

Every page on https://docs.discord.com exists as plain Markdown when ``.md`` is appended to
its URL. This script (stdlib only) mirrors the curated pages listed in ``index.md`` — or the
whole index from https://docs.discord.com/llms.txt with ``--all`` — so agents read local files
before hitting the network.

Usage (from the repo root):
    python .cursor/skills/discord-docs/scripts/fetch_discord_docs.py            # curated index
    python .cursor/skills/discord-docs/scripts/fetch_discord_docs.py --all      # everything in llms.txt
    python .cursor/skills/discord-docs/scripts/fetch_discord_docs.py --check    # report upstream changes, write nothing
    python .cursor/skills/discord-docs/scripts/fetch_discord_docs.py interactions/overview  # one slug

Output: ``docs/discord/<path>.md`` plus ``docs/discord/_SOURCE.md`` (date, page list, hashes).
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
import urllib.error
import urllib.request
from datetime import UTC, datetime
from pathlib import Path

BASE_URL = "https://docs.discord.com/developers/"
LLMS_TXT = "https://docs.discord.com/llms.txt"
USER_AGENT = "discord-bot-docs-mirror (https://github.com/notolac/discord-bot)"

SCRIPT_DIR = Path(__file__).resolve().parent
SKILL_DIR = SCRIPT_DIR.parent
REPO_ROOT = SKILL_DIR.parents[2]  # .cursor/skills/discord-docs → repo root
INDEX_MD = SKILL_DIR / "index.md"
OUTPUT_DIR = REPO_ROOT / "docs" / "discord"
SOURCE_MD = OUTPUT_DIR / "_SOURCE.md"

_URL_RE = re.compile(
    r"https://docs\.discord\.com/developers/([A-Za-z0-9_\-/.+]+?)(?:\.md)?(?=[\s)\]|>]|$)"
)


def fetch(url: str, timeout: float = 30.0) -> str:
    """HTTP GET returning text; raises ``urllib.error.URLError`` / ``HTTPError``."""
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=timeout) as response:
        return response.read().decode("utf-8")


def slugs_from_text(text: str) -> list[str]:
    """Extract unique developer-doc slugs (``interactions/overview``) from any text."""
    seen: dict[str, None] = {}
    for match in _URL_RE.finditer(text):
        slug = match.group(1).rstrip("/")
        slug = slug.split("#", 1)[0]
        if slug and slug not in seen:
            seen[slug] = None
    return list(seen)


def curated_slugs() -> list[str]:
    """Slugs listed in the skill's ``index.md``."""
    if not INDEX_MD.is_file():
        sys.exit(f"missing {INDEX_MD}")
    return slugs_from_text(INDEX_MD.read_text(encoding="utf-8"))


def all_slugs() -> list[str]:
    """Slugs from the upstream ``llms.txt`` index."""
    return slugs_from_text(fetch(LLMS_TXT))


def local_path(slug: str) -> Path:
    """Where a slug is mirrored locally."""
    return OUTPUT_DIR / f"{slug}.md"


def sha256(text: str) -> str:
    """Short content hash."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def read_existing_hashes() -> dict[str, str]:
    """Parse ``_SOURCE.md`` table into ``{slug: hash}``."""
    if not SOURCE_MD.is_file():
        return {}
    hashes: dict[str, str] = {}
    for line in SOURCE_MD.read_text(encoding="utf-8").splitlines():
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) >= 2 and re.fullmatch(r"[0-9a-f]{16}", cells[1]):
            hashes[cells[0].strip("`")] = cells[1]
    return hashes


def write_source(results: dict[str, str]) -> None:
    """Write ``_SOURCE.md`` with fetch date and per-page hashes."""
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Discord docs mirror — source",
        "",
        f"Fetched: **{now}** from `{BASE_URL}<slug>.md` (index: {LLMS_TXT}).",
        "Generated by `.cursor/skills/discord-docs/scripts/fetch_discord_docs.py`; do not edit by hand.",
        "",
        "| Slug | SHA-256 (16) | Official URL |",
        "|------|--------------|--------------|",
    ]
    for slug in sorted(results):
        lines.append(f"| `{slug}` | {results[slug]} | {BASE_URL}{slug} |")
    SOURCE_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    """CLI."""
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("slugs", nargs="*", help="specific slugs, e.g. interactions/overview")
    parser.add_argument("--all", action="store_true", help="mirror every page listed in llms.txt")
    parser.add_argument(
        "--check", action="store_true", help="compare with the local mirror, write nothing"
    )
    args = parser.parse_args(argv)

    if args.slugs:
        slugs = [s.strip("/").removesuffix(".md") for s in args.slugs]
    elif args.all:
        slugs = all_slugs()
    else:
        slugs = curated_slugs()

    previous = read_existing_hashes()
    results: dict[str, str] = dict(previous)
    changed: list[str] = []
    failed: list[str] = []

    for index, slug in enumerate(slugs, 1):
        url = f"{BASE_URL}{slug}.md"
        try:
            text = fetch(url)
        except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError) as exc:
            failed.append(f"{slug}: {exc}")
            print(f"[{index}/{len(slugs)}] FAIL {slug} ({exc})", file=sys.stderr)
            continue
        digest = sha256(text)
        status = (
            "new" if slug not in previous else ("changed" if previous[slug] != digest else "same")
        )
        if status != "same":
            changed.append(f"{slug} ({status})")
        print(f"[{index}/{len(slugs)}] {status:7} {slug}")
        if not args.check:
            path = local_path(slug)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            results[slug] = digest

    if not args.check:
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        write_source(results)
        print(
            f"\nmirrored {len(slugs) - len(failed)} page(s) into {OUTPUT_DIR.relative_to(REPO_ROOT)}/"
        )
    else:
        print(
            f"\n{len(changed)} page(s) differ from the local mirror"
            if changed
            else "\nlocal mirror is up to date"
        )

    if failed:
        print(f"{len(failed)} page(s) failed:", file=sys.stderr)
        for item in failed:
            print(f"  - {item}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
